### PR TITLE
adding version option to unshare a specific version of cookbook

### PR DESCRIPTION
**Pull request by deepsihag**
Currently unshare subcommand will unshare/delete all the version of cookbook, With this change a specific version can be specified for the cookbook to delete

### CODE REVIEW

**Comment by nellshamrell** [comment]
Thank you for this contribution.  Unfortunately, we are unable to merge it at this time.  This is because the "will we won't we" allow a user to yank a specific version of a cookbook is still under discussion https://github.com/chef/supermarket/issues/954#issuecomment-144824279

However, I will be sure to bring this up in an RFC to be discussed at the next Chef Community meeting.

**Comment by deepsihag** [comment]
@nellshamrell , thanks for update.
So there is API endpoint available to delete a specific version of cookbook from supermarket. https://docs.chef.io/api_cookbooks_site.html#id2
So is it possible that this API endpoint might get removed?

**Comment by nellshamrell** [comment]
Hi @deepsihag! It depends on what is decided at the community meeting (or over the course of several meetings, as is sometimes the case).  I will update here when I know!

**Comment by nellshamrell** [comment]
I've opened an RFC around this issue here https://github.com/chef/chef-rfc/pull/190 and it will be discussed at tomorrow's community RFC meeting (or, if not tomorrow's, at a community RFC meeting in the near future).

**Pull request closed without merging**
